version: '3.4'

services:
  infinity:
    image: infinity
    command: "gunicorn -w 4 app:app"
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:${PORT}
